import json
dict_ = {}
dict_["Dense"] = {}
dict_["Dense"]["required"] = ["units"]
dict_["Dense"]["optional"] = ["input_shape", "activation", "use_bias", "kernel_initializer", "bias_initializer", "kernel_regularizer", "bias_regularizer", "activity_regularizer", "kernel_constraint", "bias_constraint"]
dict_["Activation"] = {}
dict_["Activation"]["required"] = ["activation"]
dict_["Activation"]["optional"] = ["input_shape"]
dict_["Dropout"] = {}
dict_["Dropout"]["required"] = ["rate"]
dict_["Dropout"]["optional"] = ["noise_shape", "seed", "input_shape"]
dict_["Flatten"] = {}
dict_["Flatten"]["required"] = []
dict_["Flatten"]["optional"] = ["input_shape"]
dict_["Reshape"] = {}
dict_["Reshape"]["required"] = ["target_shape"]
dict_["Reshape"]["optional"] = ["input_shape"]
dict_["Permute"] = {}
dict_["Permute"]["required"] = ["dims"]
dict_["Permute"]["optional"] = ["input_shape"]
dict_["RepeatVector"] = {}
dict_["RepeatVector"]["required"] = ["n"]
dict_["RepeatVector"]["optional"] = []
dict_["Lambda"] = {}
dict_["Lambda"]["required"] = ["function"]
dict_["Lambda"]["optional"] = ["output_shape", "mask", "arguments", "input_shape"]
dict_["ActivityRegularization"] = {}
dict_["ActivityRegularization"]["required"] = ["l1", "l2"]
dict_["ActivityRegularization"]["optional"] = ["input_shape"]
dict_["Masking"] = {}
dict_["Masking"]["required"] = ["mask_value"]
dict_["Masking"]["optional"] = ["input_shape"]
dict_["Conv1D"] = {}
dict_["Conv1D"]["required"] = ["filters", "kernel_size"]
dict_["Conv1D"]["optional"] = ["input_shape", "strides", "padding", "dilation_rate", "activation", "use_bias", "kernel_initializer", "bias_initializer", "kernel_regularizer", "bias_regularizer", "activity_regularizer", "kernel_constraint", "bias_constraint"]
dict_["Conv2D"] = {}
dict_["Conv2D"]["required"] = ["filters", "kernel_size"]
dict_["Conv2D"]["optional"] = ["input_shape", "strides", "padding", "data_format", "dilation_rate", "activation", "use_bias", "kernel_initializer", "bias_initializer", "kernel_regularizer", "bias_regularizer", "activity_regularizer", "kernel_constraint", "bias_constraint"]
dict_["MaxPooling1D"] = {}
dict_["MaxPooling1D"]["required"] = []
dict_["MaxPooling1D"]["optional"] = ["pool_size", "strides", "padding", "input_shape"]
dict_["MaxPooling2D"] = {}
dict_["MaxPooling2D"]["required"] = []
dict_["MaxPooling2D"]["optional"] = ["pool_size", "strides", "padding", "data_format", "input_shape"]
dict_["SimpleRNN"] = {}
dict_["SimpleRNN"]["required"] = ["units"]
dict_["SimpleRNN"]["optional"] = ["activation", "use_bias", "kernel_initializer", "recurrent_initializer", "bias_initializer", "kernel_regularizer", "recurrent_regularizer", "bias_regularizer", "activity_regularizer", "kernel_constraint", "bias_constraint", "recurrent_constraint", "dropout", "recurrent_dropout"]
dict_["GRU"] = {}
dict_["GRU"]["required"] = ["units"]
dict_["GRU"]["optional"] = ["activation", "recurrent_activation", "use_bias", "kernel_initializer", "recurrent_initializer", "bias_initializer", "kernel_regularizer", "recurrent_regularizer", "bias_regularizer", "activity_regularizer", "kernel_constraint", "bias_constraint", "recurrent_constraint", "dropout", "recurrent_dropout"]
dict_["LSTM"] = {}
dict_["LSTM"]["required"] = ["units"]
dict_["LSTM"]["optional"] = ["activation", "recurrent_activation", "use_bias", "kernel_initializer", "recurrent_initializer", "bias_initializer", "kernel_regularizer", "recurrent_regularizer", "bias_regularizer", "activity_regularizer", "kernel_constraint", "bias_constraint", "recurrent_constraint", "dropout", "recurrent_dropout"]
with open('layers.json', 'w') as outfile:
     json.dump(dict_, outfile, indent = 4)